export const blogs = [{
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        textFull: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quos ullam dolorum quia dolores fugit vel mollitia distinctio qui. Praesentium aperiam in incidunt nostrum error explicabo tempora maiores corrupti eos dolorem eligendi sunt placeat, quia et nihil non autem totam accusantium ut nemo! Totam recusandae, aut ut obcaecati delectus nemo, officia accusamus nulla dolores at suscipit tempore! Explicabo, assumenda itaque quos reiciendis unde quo earum. Officiis cum atque adipisci nostrum non explicabo culpa nemo. Repellat reprehenderit consequatur et recusandae adipisci dolorem laborum. Sunt impedit sint, nesciunt adipisci repellendus dignissimos sit similique ipsam sed debitis maxime, consequatur unde, consequuntur error fuga.',
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        textFull: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quos ullam dolorum quia dolores fugit vel mollitia distinctio qui. Praesentium aperiam in incidunt nostrum error explicabo tempora maiores corrupti eos dolorem eligendi sunt placeat, quia et nihil non autem totam accusantium ut nemo! Totam recusandae, aut ut obcaecati delectus nemo, officia accusamus nulla dolores at suscipit tempore! Explicabo, assumenda itaque quos reiciendis unde quo earum. Officiis cum atque adipisci nostrum non explicabo culpa nemo. Repellat reprehenderit consequatur et recusandae adipisci dolorem laborum. Sunt impedit sint, nesciunt adipisci repellendus dignissimos sit similique ipsam sed debitis maxime, consequatur unde, consequuntur error fuga.',
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        textFull: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quos ullam dolorum quia dolores fugit vel mollitia distinctio qui. Praesentium aperiam in incidunt nostrum error explicabo tempora maiores corrupti eos dolorem eligendi sunt placeat, quia et nihil non autem totam accusantium ut nemo! Totam recusandae, aut ut obcaecati delectus nemo, officia accusamus nulla dolores at suscipit tempore! Explicabo, assumenda itaque quos reiciendis unde quo earum. Officiis cum atque adipisci nostrum non explicabo culpa nemo. Repellat reprehenderit consequatur et recusandae adipisci dolorem laborum. Sunt impedit sint, nesciunt adipisci repellendus dignissimos sit similique ipsam sed debitis maxime, consequatur unde, consequuntur error fuga.',
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        textFull: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quos ullam dolorum quia dolores fugit vel mollitia distinctio qui. Praesentium aperiam in incidunt nostrum error explicabo tempora maiores corrupti eos dolorem eligendi sunt placeat, quia et nihil non autem totam accusantium ut nemo! Totam recusandae, aut ut obcaecati delectus nemo, officia accusamus nulla dolores at suscipit tempore! Explicabo, assumenda itaque quos reiciendis unde quo earum. Officiis cum atque adipisci nostrum non explicabo culpa nemo. Repellat reprehenderit consequatur et recusandae adipisci dolorem laborum. Sunt impedit sint, nesciunt adipisci repellendus dignissimos sit similique ipsam sed debitis maxime, consequatur unde, consequuntur error fuga.',
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        textFull: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quos ullam dolorum quia dolores fugit vel mollitia distinctio qui. Praesentium aperiam in incidunt nostrum error explicabo tempora maiores corrupti eos dolorem eligendi sunt placeat, quia et nihil non autem totam accusantium ut nemo! Totam recusandae, aut ut obcaecati delectus nemo, officia accusamus nulla dolores at suscipit tempore! Explicabo, assumenda itaque quos reiciendis unde quo earum. Officiis cum atque adipisci nostrum non explicabo culpa nemo. Repellat reprehenderit consequatur et recusandae adipisci dolorem laborum. Sunt impedit sint, nesciunt adipisci repellendus dignissimos sit similique ipsam sed debitis maxime, consequatur unde, consequuntur error fuga.',
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        textFull: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quos ullam dolorum quia dolores fugit vel mollitia distinctio qui. Praesentium aperiam in incidunt nostrum error explicabo tempora maiores corrupti eos dolorem eligendi sunt placeat, quia et nihil non autem totam accusantium ut nemo! Totam recusandae, aut ut obcaecati delectus nemo, officia accusamus nulla dolores at suscipit tempore! Explicabo, assumenda itaque quos reiciendis unde quo earum. Officiis cum atque adipisci nostrum non explicabo culpa nemo. Repellat reprehenderit consequatur et recusandae adipisci dolorem laborum. Sunt impedit sint, nesciunt adipisci repellendus dignissimos sit similique ipsam sed debitis maxime, consequatur unde, consequuntur error fuga.',
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
];
export const portfolios = {
    logo: ["src", "src", "src"],
    video: ["src", "src", "src"],
    graphicDesign: ["src", "src", "src"],
};